// lib/achievements/achievementsConfig.ts
import { Achievement } from "@/app/types/achievements";

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "first_project",
    title: "Project Starter",
    description: "Create your first project",
    icon: "ProjectIcon",
    requirement: 1,
    requirementType: "projects_created",
    category: "projects",
    points: 100,
    badgeColor: "#E8610A",
  },
  {
    id: "project_master",
    title: "Project Master",
    description: "Create 5 projects",
    icon: "ProjectIcon",
    requirement: 5,
    requirementType: "projects_created",
    category: "projects",
    points: 500,
    badgeColor: "#E8610A",
  },
  {
    id: "project_legend",
    title: "Project Legend",
    description: "Create 10 projects",
    icon: "ProjectIcon",
    requirement: 10,
    requirementType: "projects_created",
    category: "projects",
    points: 1000,
    badgeColor: "#E8610A",
  },
  {
    id: "project_completer",
    title: "Project Completer",
    description: "Complete 3 projects (all tasks done)",
    icon: "ProjectIcon",
    requirement: 3,
    requirementType: "projects_completed",
    category: "projects",
    points: 600,
    badgeColor: "#E8610A",
  },
  {
    id: "project_architect",
    title: "Project Architect",
    description: "Create 25 projects",
    icon: "RocketIcon",
    requirement: 25,
    requirementType: "projects_created",
    category: "projects",
    points: 2000,
    badgeColor: "#C2410C",
  },
  {
    id: "project_finisher",
    title: "Finisher",
    description: "Complete your first project",
    icon: "SparklesIcon",
    requirement: 1,
    requirementType: "projects_completed",
    category: "projects",
    points: 250,
    badgeColor: "#EA580C",
  },
  {
    id: "serial_completer",
    title: "Serial Completer",
    description: "Complete 10 projects",
    icon: "RocketIcon",
    requirement: 10,
    requirementType: "projects_completed",
    category: "projects",
    points: 1500,
    badgeColor: "#C2410C",
  },
  {
    id: "project_visionary",
    title: "Visionary",
    description: "Create 50 projects",
    icon: "WorkspacesIcon",
    requirement: 50,
    requirementType: "projects_created",
    category: "projects",
    points: 3500,
    badgeColor: "#9A3412",
  },
  {
    id: "completionist",
    title: "Completionist",
    description: "Complete 25 projects",
    icon: "TrophyIcon",
    requirement: 25,
    requirementType: "projects_completed",
    category: "projects",
    points: 3000,
    badgeColor: "#9A3412",
  },
  {
    id: "task_novice",
    title: "Task Novice",
    description: "Complete 10 tasks",
    icon: "TaskIcon",
    requirement: 10,
    requirementType: "tasks_completed",
    category: "tasks",
    points: 100,
    badgeColor: "#10B981",
  },
  {
    id: "task_machine",
    title: "Task Machine",
    description: "Complete 50 tasks",
    icon: "TaskIcon",
    requirement: 50,
    requirementType: "tasks_completed",
    category: "tasks",
    points: 500,
    badgeColor: "#10B981",
  },
  {
    id: "task_terminator",
    title: "Task Terminator",
    description: "Complete 100 tasks",
    icon: "TaskIcon",
    requirement: 100,
    requirementType: "tasks_completed",
    category: "tasks",
    points: 1000,
    badgeColor: "#10B981",
  },
  {
    id: "task_creator",
    title: "Task Creator",
    description: "Create 20 tasks across your projects",
    icon: "TaskIcon",
    requirement: 20,
    requirementType: "tasks_created",
    category: "tasks",
    points: 300,
    badgeColor: "#10B981",
  },
  {
    id: "first_task",
    title: "Getting Started",
    description: "Complete your very first task",
    icon: "TaskIcon",
    requirement: 1,
    requirementType: "tasks_completed",
    category: "tasks",
    points: 50,
    badgeColor: "#34D399",
  },
  {
    id: "task_factory",
    title: "Task Factory",
    description: "Create 100 tasks across your projects",
    icon: "LightningIcon",
    requirement: 100,
    requirementType: "tasks_created",
    category: "tasks",
    points: 800,
    badgeColor: "#059669",
  },
  {
    id: "task_legend",
    title: "Task Legend",
    description: "Complete 250 tasks",
    icon: "LightningIcon",
    requirement: 250,
    requirementType: "tasks_completed",
    category: "tasks",
    points: 2500,
    badgeColor: "#047857",
  },
  {
    id: "task_overlord",
    title: "Task Overlord",
    description: "Complete 500 tasks",
    icon: "ChartIcon",
    requirement: 500,
    requirementType: "tasks_completed",
    category: "tasks",
    points: 4000,
    badgeColor: "#065F46",
  },
  {
    id: "prolific_planner",
    title: "Prolific Planner",
    description: "Create 250 tasks across your projects",
    icon: "ChartIcon",
    requirement: 250,
    requirementType: "tasks_created",
    category: "tasks",
    points: 1500,
    badgeColor: "#065F46",
  },
  {
    id: "consistency",
    title: "Consistency",
    description: "Active for 7 days in a row",
    icon: "StreakIcon",
    requirement: 7,
    requirementType: "days_active",
    category: "streak",
    points: 300,
    badgeColor: "#8B5CF6",
  },
  {
    id: "dedication",
    title: "Dedication",
    description: "Active for 30 days",
    icon: "StreakIcon",
    requirement: 30,
    requirementType: "days_active",
    category: "streak",
    points: 1000,
    badgeColor: "#8B5CF6",
  },
  {
    id: "first_day",
    title: "Day One",
    description: "Show up for the first time",
    icon: "CalendarIcon",
    requirement: 1,
    requirementType: "days_active",
    category: "streak",
    points: 25,
    badgeColor: "#A78BFA",
  },
  {
    id: "half_century",
    title: "Centurion",
    description: "Active for 100 days",
    icon: "StreakIcon",
    requirement: 100,
    requirementType: "days_active",
    category: "streak",
    points: 3000,
    badgeColor: "#6D28D9",
  },
  {
    id: "fortnight_fan",
    title: "Fortnight Fan",
    description: "Active for 14 days",
    icon: "CalendarIcon",
    requirement: 14,
    requirementType: "days_active",
    category: "streak",
    points: 500,
    badgeColor: "#7C3AED",
  },
  {
    id: "year_long_devotee",
    title: "Year-Long Devotee",
    description: "Active for 365 days",
    icon: "StreakIcon",
    requirement: 365,
    requirementType: "days_active",
    category: "streak",
    points: 10000,
    badgeColor: "#5B21B6",
  },
  {
    id: "team_player",
    title: "Team Player",
    description: "Add 3 team members to your projects",
    icon: "SocialIcon",
    requirement: 3,
    requirementType: "team_members_added",
    category: "social",
    points: 200,
    badgeColor: "#3B82F6",
  },
  {
    id: "first_invite",
    title: "Better Together",
    description: "Add your first team member",
    icon: "SocialIcon",
    requirement: 1,
    requirementType: "team_members_added",
    category: "social",
    points: 75,
    badgeColor: "#60A5FA",
  },
  {
    id: "squad_goals",
    title: "Squad Goals",
    description: "Add 10 team members across your projects",
    icon: "SocialIcon",
    requirement: 10,
    requirementType: "team_members_added",
    category: "social",
    points: 600,
    badgeColor: "#2563EB",
  },
  {
    id: "community_builder",
    title: "Community Builder",
    description: "Add 25 team members across your projects",
    icon: "SocialIcon",
    requirement: 25,
    requirementType: "team_members_added",
    category: "social",
    points: 1200,
    badgeColor: "#1D4ED8",
  },
  {
    id: "network_effect",
    title: "Network Effect",
    description: "Add 50 team members across your projects",
    icon: "LeaderboardIcon",
    requirement: 50,
    requirementType: "team_members_added",
    category: "social",
    points: 2200,
    badgeColor: "#1E40AF",
  },
  {
    id: "social_butterfly",
    title: "Social Butterfly",
    description: "Add 5 team members to your projects",
    icon: "SocialIcon",
    requirement: 5,
    requirementType: "team_members_added",
    category: "social",
    points: 350,
    badgeColor: "#3B82F6",
  },
  {
    id: "tool_explorer",
    title: "Tool Explorer",
    description: "Use 5 different tools in Tool Hub",
    icon: "ToolIcon",
    requirement: 5,
    requirementType: "tools_used",
    category: "tools",
    points: 400,
    badgeColor: "#F59E0B",
  },
  {
    id: "first_tool",
    title: "Tooled Up",
    description: "Use your first tool in Tool Hub",
    icon: "ToolIcon",
    requirement: 1,
    requirementType: "tools_used",
    category: "tools",
    points: 100,
    badgeColor: "#FCD34D",
  },
  {
    id: "tool_master",
    title: "Tool Master",
    description: "Use 15 different tools in Tool Hub",
    icon: "ToolIcon",
    requirement: 15,
    requirementType: "tools_used",
    category: "tools",
    points: 1000,
    badgeColor: "#D97706",
  },
  {
    id: "tool_connoisseur",
    title: "Tool Connoisseur",
    description: "Use 10 different tools in Tool Hub",
    icon: "ToolIcon",
    requirement: 10,
    requirementType: "tools_used",
    category: "tools",
    points: 700,
    badgeColor: "#B45309",
  },
  {
    id: "tool_grandmaster",
    title: "Tool Grandmaster",
    description: "Use 25 different tools in Tool Hub",
    icon: "WrenchIcon",
    requirement: 25,
    requirementType: "tools_used",
    category: "tools",
    points: 2000,
    badgeColor: "#92400E",
  },
];

// Helper to get achievement by ID
export const getAchievementById = (id: string): Achievement | undefined => {
  return ACHIEVEMENTS.find((a) => a.id === id);
};

// Helper to get achievements by category
export const getAchievementsByCategory = (category: string): Achievement[] => {
  return ACHIEVEMENTS.filter((a) => a.category === category);
};
